export const COMMON_REACT_EVENTS = [
  'Click',
  'Change',
  'Submit',
  'KeyDown',
  'KeyUp',
  'KeyPress',
  'Focus',
  'Blur',
  'MouseEnter',
  'MouseLeave',
  'MouseMove',
  'MouseDown',
  'MouseUp',
  'Scroll',
  'Wheel',
  'Drag',
  'Drop',
  'Load',
  'Error',
  'AnimationStart',
  'AnimationEnd',
  'TransitionEnd',
];

export const EVENT_PAST_TENSE_MAP: Record<string, string[]> = {
  Click: ['Clicked'],
  Change: ['Changed'],
  Submit: ['Submitted'],
  KeyDown: ['KeyDowned'],
  KeyUp: ['KeyUpped'],
  KeyPress: ['KeyPressed'],
  Focus: ['Focused'],
  Blur: ['Blurred'],
  MouseEnter: ['MouseEntered'],
  MouseLeave: ['MouseLeft', 'MouseLeaved'],
  MouseMove: ['MouseMoved'],
  MouseDown: ['MouseDowned'],
  MouseUp: ['MouseUpped'],
  Scroll: ['Scrolled'],
  Wheel: ['Wheeled'],
  Drag: ['Dragged'],
  Drop: ['Dropped'],
  Load: ['Loaded'],
  Error: ['Errored'],
  AnimationStart: ['AnimationStarted'],
  AnimationEnd: ['AnimationEnded'],
  TransitionEnd: ['TransitionEnded'],
};
